-- -----------------------------------------------------------------------------------------------
-- Autor/a:                      Mariela Montaldo
-- Fecha:                        26/05/2024
-- Descripción:                  Inserta registros para TP de curso JAVA - Full Stack - Com. 24100
-- -----------------------------------------------------------------------------------------------

-- Movies

INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Pulp Fiction',SUBSTRING('Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.',1,255),'Suspense,Crimen',85,'1995',5,'Quentin Tarantino');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Toro salvaje',SUBSTRING('Jake la Motta es un joven boxeador que se entrena duramente, ayudado por su hermano Joey, para convertirse en el número uno de los pesos medios. Pronto consigue ver hecho realidad tan ansiado sueño, pero el triunfo y el éxito convierten su vida en una pesadilla. Por un lado, su matrimonio cada vez marcha peor debido a sus salidas nocturnas con otras mujeres; por otro, la mafia le presiona para que amañe combates. En poco tiempo gasta todo el capital del que dispone, para volver nuevamente a pasar todo tipo de penurias.',1,255),'Drama',79,'1980',5,'Martin Scorsese');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Hierro 3',SUBSTRING('Tae-suk es un indigente que lleva una vida espectral. Ocupa temporalmente viviendas cuyos habitantes sabe que están ausentes. No roba ni ocasiona daños en los hogares de sus involuntarios anfitriones. En realidad, es una especie de fantasma que duerme en camas ajenas, come algo de las neveras de esos extraños y retribuye su forzada hospitalidad haciendo la colada o arreglando alguna que otra avería doméstica. Sun-hwa, que en tiempos fue una hermosa modelo, se ha visto convertida en una sombra viviente por un marido que la maltrata, encerrándola en una casa ostentosa. El destino cruza los caminos de Tae-suk y Sun-hwa, aunque sus existencias están abocadas a no dejar huella en el mundo. Se conocen cuando Tae-suk entra en casa de Sun-hwa, y en seguida saben que son almas gemelas. Como si estuvieran unidos por vínculos invisibles, descubren que no pueden separarse y aceptan en silencio su nuevo y extraño destino.',1,255),'Drama,Romance,Crimen',78,'2004',4,'Kim Ki Duk');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Breakfast club',SUBSTRING('Cinco estudiantes de distinta educación, formación y gustos son castigados a pasar un sábado en el instituto en el que estudian. Pronto las desavenencias entre ellos aparecen, especialmente cuando el director que les vigila se ausenta del aula... Comedia juvenil de culto de los años ochenta.',1,255),'Comedia,Drama',77,'1985',4,'John Hughes');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Volver al futuro',SUBSTRING('Marty McFly, un estudiante de secundaria de 17 años, es enviado accidentalmente treinta años al pasado en un DeLorean que viaja en el tiempo, inventado por su gran amigo, el excéntrico científico Doc Brown.',1,255),'Aventura,Comedia,Ciencia ficción',83,'1985',5,'Robert Zemeckis');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Canino',SUBSTRING('Un matrimonio con tres hijos vive en una mansión en las afueras de una ciudad. Los chicos, que nunca han salido de casa, son educados según los métodos que sus padres juzgan más apropiados y sin recibir ninguna influencia del exterior. Creen que los aviones son juguetes o que el mar es un tipo de silla forrada de cuero. La única persona que puede entrar en la casa es Christine, guardia de seguridad en la fábrica del padre.',1,255),'Drama',71,'2009',4,'Yorgos Lanthimos');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Taxi Driver',SUBSTRING('Para sobrellevar el insomnio crónico que sufre después de su regreso de Vietnam, Travis decide trabajar como taxista nocturno. Como individuo tiene poco contacto con la gente, pero observa la violencia y desolación en la que se hunde la ciudad de Nueva York. Travis anota en su diario todas sus impresiones, hasta que un día decide pasar a la acción.',1,255),'Crimen,Drama',82,'1976',5,'Martin Scorsese');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Terminator II: El juicio final',SUBSTRING('Ha pasado once años desde que Sarah Connor fue marcada como objetivo para ser eliminada por un cyborg del futuro. Ahora su hijo John, el futuro líder de la resistencia, es el objetivo de un Terminator más moderno, más mortífero. Una vez más, la resistencia se las ha ingeniado para enviar un protector de vuelta al pasado para intentar salvar a John y a su madre Sarah.',1,255),'Acción,Suspense,Ciencia ficción',81,'1991',5,'James Cameron');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Turbulencia III: Secuestro en la red',SUBSTRING('Terroristas toman un avión que esta trasmitiendo un concierto en vivo de Rock por Internet.',1,255),'Acción,Suspense',41,'2001',3,'Jorge Montesi');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Millenium 1',SUBSTRING('Un rico industrial llamado Henrik Vanger (Sven-Bertil Taube) contrata al periodista Mikael Blomqvist (Michael Nyqvist) para que averigüe qué fue de su sobrina Harriet, que desapareció sin dejar rastro hace 40 años. Adaptación al cine de la primera parte de la trilogía "Millenium" del escritor sueco Stieg Larsson.',1,255),'Drama,Suspense,Crimen,Misterio',75,'2009',4,'Niels Arden Oplev');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Kill Bill: Vol I',SUBSTRING('Uma Thurman es una asesina que, el día de su boda, es atacada por los miembros de la banda de su jefe, Bill (David Carradine). Logra sobrevivir al ataque, aunque queda en coma. Cinco años después despierta con un trozo de metal en la cabeza y un gran deseo de venganza en su corazón.',1,255),'Acción,Crimen',80,'2003',3.5,'Quentin Tarantino');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Vivir',SUBSTRING('La anécdota parece desgarradoramente simple: un hombre descubre que está enfermo y finalmente muere. Pero en su funeral coinciden varios parientes y conocidos que comienzan a reconstruir los últimos meses de su vida y descubren que sus últimos actos han tenido un sentido íntimo y personal. Con este film Kurosawa demostró que podía jugar mano a mano en el terreno de las emociones, más relacionado por lo general con maestros como Ozu o Mizoguchi. Todo el film es un milagro de sutileza, conducido por el rostro adusto del protagonista Shimura (que por otra parte no tenía problemas en aparecer en las películas de monstruos de Ishiro Honda), pero su última secuencia debe contarse entre los más grandes momentos del cine todo. Fue el primer largometraje de Kurosawa exhibido por la TV argentina, en canal 11, un lunes de 1963.',1,255),'Drama',88,'1952',5,'Akira Kurosawa');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Aftersun',SUBSTRING('Sophie reflexiona sobre la alegría y melancolía de unas vacaciones que tomó con su padre veinte años antes. Los recuerdos reales o no, llenan los espacios mientras intenta reconciliar al padre que conoció con el hombre que no conocía.',1,255),'Drama',95,'2022',4,'Charlotte Wells');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Whiplash',SUBSTRING('El objetivo de Andrew Neiman, un joven y ambicioso baterista de jazz, es triunfar en el elitista Conservatorio de Música de la Costa Este en el que estudia. Marcado por el fracaso de la carrera literaria de su padre, Andrew alberga sueños de grandeza. Terence Fletcher, un profesor conocido tanto por su talento como por sus rigurosos métodos de enseñanza, dirige el mejor conjunto de jazz del Conservatorio. Cuando Fletcher elige a Andrew y para formar parte del conjunto musical que dirige, cambia para siempre la vida del joven. La pasión de Andrew por alcanzar la perfección se convierte en obsesión, al tiempo que su despiadado profesor lo lleva al límite de su capacidad y de su salud mental.',1,255),'Drama,Música',84,'2014',5,'Damien Chazelle');
INSERT INTO movies (nombre,descripcion,genero,calificacion,año,estrellas,director) VALUES ('Babel',SUBSTRING('Ambientada en Marruecos, Túnez, México y Japón. Armados con un Winchester, dos muchachos marroquíes salen en busca del rebaño de cabras de la familia. En medio del silencio del desierto, deciden probar el rifle, sin conocer el alcance de la bala. En un instante, entran en colisión las vidas de cuatro grupos de personas que viven en tres continentes distintos.',1,255),'Drama',72,'2006',5,'Alejandro González Iñárritu');